# Generated by Django 2.2 on 2019-08-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'altertable'),
        ('home', '0005_signup'),
    ]

    operations = [
    ]
