# Generated by Django 2.2 on 2019-08-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'verbose_name_plural': 'Information'},
        ),
    ]
