# Generated by Django 2.2 on 2019-08-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('home','0002_auto_20190808_0622'),
    ]

    operations = [
        migrations.RenameModel("Introduction", "Information")
    ]
